# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration
require:
  - rubocop-rails

Style/Documentation:
  Enabled: false #この規則は、すべてのクラスとモジュールの定義の直前にドキュメントのコメントが必要であると要求します。

Metrics/AbcSize:
  Max: 35 # 値を大きくして複雑さの許容度を上げる

Metrics/MethodLength:
  Max: 40 # メソッドの長さの許容度を上げる
